# Generated by Django 2.1.7 on 2019-04-11 17:44

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='files/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'afiliado',
            },
        ),
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto')),
                ('text_pt_br', models.TextField(null=True, verbose_name='Texto')),
                ('text_en', models.TextField(null=True, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'solução',
                'verbose_name_plural': 'soluções',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='files/', verbose_name='Imagem')),
                ('publication_date', models.DateField(default=datetime.datetime.now, verbose_name='Data de Publicação')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Título')),
                ('title_pt_br', models.CharField(default='', max_length=100, null=True, verbose_name='Título')),
                ('title_en', models.CharField(default='', max_length=100, null=True, verbose_name='Título')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Descrição')),
                ('description_pt_br', ckeditor_uploader.fields.RichTextUploadingField(default='', null=True, verbose_name='Descrição')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(default='', null=True, verbose_name='Descrição')),
                ('is_highlight', models.BooleanField(default=False, verbose_name='Em Destaque')),
            ],
            options={
                'verbose_name': 'prêmio',
                'ordering': ['-is_highlight'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Horário')),
                ('description_short', models.TextField(default='', verbose_name='Descrição Curta')),
                ('description_short_pt_br', models.TextField(default='', null=True, verbose_name='Descrição Curta')),
                ('description_short_en', models.TextField(default='', null=True, verbose_name='Descrição Curta')),
                ('description', models.TextField(default='', verbose_name='Descrição')),
                ('description_pt_br', models.TextField(default='', null=True, verbose_name='Descrição')),
                ('description_en', models.TextField(default='', null=True, verbose_name='Descrição')),
                ('country', models.CharField(blank=True, max_length=2, null=True, verbose_name='País')),
                ('country_pt_br', models.CharField(blank=True, max_length=2, null=True, verbose_name='País')),
                ('country_en', models.CharField(blank=True, max_length=2, null=True, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('city_pt_br', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('city_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('address', models.CharField(default='', max_length=200, verbose_name='Endereço')),
                ('address_pt_br', models.CharField(default='', max_length=200, null=True, verbose_name='Endereço')),
                ('address_en', models.CharField(default='', max_length=200, null=True, verbose_name='Endereço')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='files/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'evento',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('name_pt_br', models.CharField(max_length=50, null=True, verbose_name='Nome')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'título da função',
                'verbose_name_plural': 'titulos das funções',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('name_pt_br', models.CharField(max_length=50, null=True, unique=True, verbose_name='Nome')),
                ('name_en', models.CharField(max_length=50, null=True, unique=True, verbose_name='Nome')),
                ('flag', models.ImageField(upload_to='files/', verbose_name='Bandeira')),
            ],
            options={
                'verbose_name': 'idioma',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='Sobrenome')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='files/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'membro',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='MemberAdministrativeStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='portal.JobTitle', verbose_name='Nome da Função')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_staff', to='portal.Member')),
            ],
            options={
                'verbose_name': 'membro da equipe administrativa',
                'verbose_name_plural': 'membros da equipe administrativa',
                'ordering': ['member__first_name'],
            },
            bases=(models.Model, members.models.MemberChild),
        ),
        migrations.CreateModel(
            name='MemberIntern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intern', to='portal.Member')),
            ],
            options={
                'verbose_name': 'estagiário',
                'ordering': ['member__first_name'],
            },
            bases=(models.Model, members.models.MemberChild),
        ),
        migrations.CreateModel(
            name='MemberLawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('profile', models.TextField(verbose_name='Perfil')),
                ('profile_pt_br', models.TextField(null=True, verbose_name='Perfil')),
                ('profile_en', models.TextField(null=True, verbose_name='Perfil')),
                ('academic_formation', models.TextField(verbose_name='Formação Acadêmica')),
                ('academic_formation_pt_br', models.TextField(null=True, verbose_name='Formação Acadêmica')),
                ('academic_formation_en', models.TextField(null=True, verbose_name='Formação Acadêmica')),
                ('professional_experience', models.TextField(verbose_name='Experiência Profisisonal')),
                ('professional_experience_pt_br', models.TextField(null=True, verbose_name='Experiência Profisisonal')),
                ('professional_experience_en', models.TextField(null=True, verbose_name='Experiência Profisisonal')),
                ('awards_and_publications', models.TextField(verbose_name='Prêmios e Publicações')),
                ('awards_and_publications_pt_br', models.TextField(null=True, verbose_name='Prêmios e Publicações')),
                ('awards_and_publications_en', models.TextField(null=True, verbose_name='Prêmios e Publicações')),
                ('languages', models.ManyToManyField(related_name='lawyers', to='portal.Language', verbose_name='Idiomas')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer', to='portal.Member')),
            ],
            options={
                'verbose_name': 'advogado',
                'ordering': ['member__first_name'],
            },
            bases=(models.Model, members.models.MemberChild),
        ),
        migrations.CreateModel(
            name='MemberTrainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainee', to='portal.Member')),
            ],
            options={
                'verbose_name': 'trainee',
                'ordering': ['member__first_name'],
            },
            bases=(models.Model, members.models.MemberChild),
        ),
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('name_pt_br', models.CharField(max_length=50, null=True, verbose_name='Nome')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'tipo de membro',
                'verbose_name_plural': 'tipos de membro',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Brasil', max_length=50, verbose_name='País')),
                ('country_pt_br', models.CharField(default='Brasil', max_length=50, null=True, verbose_name='País')),
                ('country_en', models.CharField(default='Brasil', max_length=50, null=True, verbose_name='País')),
                ('state', models.CharField(default='', max_length=50, verbose_name='Estado')),
                ('state_pt_br', models.CharField(default='', max_length=50, null=True, verbose_name='Estado')),
                ('state_en', models.CharField(default='', max_length=50, null=True, verbose_name='Estado')),
                ('city', models.CharField(default='', max_length=50, verbose_name='Cidade')),
                ('city_pt_br', models.CharField(default='', max_length=50, null=True, verbose_name='Cidade')),
                ('city_en', models.CharField(default='', max_length=50, null=True, verbose_name='Cidade')),
                ('neighborhood', models.CharField(default='', max_length=50, verbose_name='Bairro')),
                ('neighborhood_pt_br', models.CharField(default='', max_length=50, null=True, verbose_name='Bairro')),
                ('neighborhood_en', models.CharField(default='', max_length=50, null=True, verbose_name='Bairro')),
                ('address', models.CharField(default='', max_length=200, verbose_name='Endereço')),
                ('address_pt_br', models.CharField(default='', max_length=200, null=True, verbose_name='Endereço')),
                ('address_en', models.CharField(default='', max_length=200, null=True, verbose_name='Endereço')),
                ('gmaps_iframe', models.CharField(default='', max_length=500, verbose_name='Iframe Embbedado do Google')),
                ('postcode', models.CharField(default='', max_length=10, verbose_name='CEP')),
                ('phone', models.CharField(default='', max_length=19, verbose_name='Telefone')),
                ('email', models.CharField(default='', max_length=50, verbose_name='E-mail')),
                ('is_parent', models.BooleanField(default=False, verbose_name='Matriz')),
            ],
            options={
                'verbose_name': 'escritório',
                'ordering': ['-is_parent'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Título')),
                ('title_pt_br', models.CharField(default='', max_length=50, null=True, verbose_name='Título')),
                ('title_en', models.CharField(default='', max_length=50, null=True, verbose_name='Título')),
                ('city', models.CharField(default='', max_length=50, verbose_name='Cidade')),
                ('city_pt_br', models.CharField(default='', max_length=50, null=True, verbose_name='Cidade')),
                ('city_en', models.CharField(default='', max_length=50, null=True, verbose_name='Cidade')),
                ('description_short', models.TextField(default='', verbose_name='Descrição Curta')),
                ('description_short_pt_br', models.TextField(default='', null=True, verbose_name='Descrição Curta')),
                ('description_short_en', models.TextField(default='', null=True, verbose_name='Descrição Curta')),
                ('description', models.TextField(default='', verbose_name='Descrição')),
                ('description_pt_br', models.TextField(default='', null=True, verbose_name='Descrição')),
                ('description_en', models.TextField(default='', null=True, verbose_name='Descrição')),
                ('spots', models.IntegerField(default=0, verbose_name='Vagas')),
            ],
            options={
                'verbose_name': 'oportunidade',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Título')),
                ('title_pt_br', models.CharField(max_length=50, null=True, unique=True, verbose_name='Título')),
                ('title_en', models.CharField(max_length=50, null=True, unique=True, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='files/', verbose_name='Imagem de Fundo')),
            ],
            options={
                'verbose_name': 'página',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PageParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=30, verbose_name='Nome')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Valor')),
                ('value_pt_br', models.TextField(blank=True, null=True, verbose_name='Valor')),
                ('value_en', models.TextField(blank=True, null=True, verbose_name='Valor')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Arquivo')),
                ('file_pt_br', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Arquivo')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Arquivo')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='portal.Page', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'parâmetro de página',
                'verbose_name_plural': 'parâmetros de página',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='files/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'parceiro',
            },
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('name_pt_br', models.CharField(max_length=50, null=True, unique=True, verbose_name='Nome')),
                ('name_en', models.CharField(max_length=50, null=True, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('description_pt_br', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='files/', verbose_name='Imagem')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Arquivo')),
                ('file_pt_br', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Arquivo')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'área de atuação',
                'verbose_name_plural': 'áreas de atuação',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Criação')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Título')),
                ('title_pt_br', models.CharField(default='', max_length=50, null=True, verbose_name='Título')),
                ('title_en', models.CharField(default='', max_length=50, null=True, verbose_name='Título')),
                ('title_internal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Título Interno')),
                ('description_short', models.TextField(default='', verbose_name='Descrição Curta')),
                ('description_short_pt_br', models.TextField(default='', null=True, verbose_name='Descrição Curta')),
                ('description_short_en', models.TextField(default='', null=True, verbose_name='Descrição Curta')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('description_pt_br', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='files/', verbose_name='Imagem')),
                ('author', models.CharField(default='', max_length=100, verbose_name='Autor')),
                ('vehicle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Veículo')),
                ('file', models.FileField(blank=True, default='', max_length=50, null=True, upload_to='', verbose_name='Arquivo')),
                ('file_pt_br', models.FileField(blank=True, default='', max_length=50, null=True, upload_to='', verbose_name='Arquivo')),
                ('file_en', models.FileField(blank=True, default='', max_length=50, null=True, upload_to='', verbose_name='Arquivo')),
                ('related_members', models.ManyToManyField(blank=True, related_name='related_publications', to='portal.Member', verbose_name='Membros Relacionados')),
            ],
            options={
                'verbose_name': 'publicação',
                'verbose_name_plural': 'publicações',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nome')),
                ('name_pt_br', models.CharField(default='', max_length=50, null=True, verbose_name='Nome')),
                ('name_en', models.CharField(default='', max_length=50, null=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'tipo de publicação',
                'verbose_name_plural': 'tipos de publicação',
            },
        ),
        migrations.CreateModel(
            name='SiteParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=30, unique=True, verbose_name='Nome')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Valor')),
                ('value_pt_br', models.TextField(blank=True, null=True, verbose_name='Valor')),
                ('value_en', models.TextField(blank=True, null=True, verbose_name='Valor')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Arquivo')),
                ('file_pt_br', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Arquivo')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'parâmetro do site',
                'verbose_name_plural': 'parâmetros do site',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocialEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nome')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='files/', verbose_name='Imagem')),
                ('description', models.TextField(default='', verbose_name='Descrição')),
                ('description_pt_br', models.TextField(default='', null=True, verbose_name='Descrição')),
                ('description_en', models.TextField(default='', null=True, verbose_name='Descrição')),
                ('site', models.URLField(default='', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'entidade social',
                'verbose_name_plural': 'entidades sociais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecializationSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('name_pt_br', models.CharField(max_length=50, null=True, unique=True, verbose_name='Nome')),
                ('name_en', models.CharField(max_length=50, null=True, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('description_pt_br', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='files/', verbose_name='Imagem')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Arquivo')),
                ('file_pt_br', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Arquivo')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'setor de especialização',
                'verbose_name_plural': 'setores de especialização',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='portal.PublicationType', verbose_name='Tipo de Publicação'),
        ),
        migrations.AddField(
            model_name='membertrainee',
            name='practice_areas',
            field=models.ManyToManyField(related_name='trainees', to='portal.PracticeArea', verbose_name='Áreas de Atuação'),
        ),
        migrations.AddField(
            model_name='memberlawyer',
            name='practice_areas',
            field=models.ManyToManyField(related_name='lawyers', to='portal.PracticeArea', verbose_name='Áreas de Atuação'),
        ),
        migrations.AddField(
            model_name='memberintern',
            name='practice_areas',
            field=models.ManyToManyField(related_name='interns', to='portal.PracticeArea'),
        ),
        migrations.AddField(
            model_name='member',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='portal.MemberType', verbose_name='Tipo de Membro'),
        ),
        migrations.AddField(
            model_name='approach',
            name='practice_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approaches', to='portal.PracticeArea', verbose_name='Área de Atuação'),
        ),
        migrations.AlterUniqueTogether(
            name='pageparameter',
            unique_together={('page', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='approach',
            unique_together={('practice_area', 'text')},
        ),
    ]
