# Generated by Django 2.1.7 on 2019-02-25 19:09

from django.contrib.auth.hashers import make_password
from django.db import migrations


def load_initial_user(apps, schema_editor):
    User = apps.get_model("auth", "User")
    capyba = User()
    capyba.is_active = True
    capyba.is_superuser = True
    capyba.is_staff = True
    capyba.username = "capyba"
    capyba.email = ""
    capyba.password = make_password("capyba")
    capyba.save()


def load_initial_members_types(apps, schema_editor):
    MemberType = apps.get_model("portal", "MemberType")
    MemberType.objects.create(name_pt_br="Advogado", name_en="Lawyer")
    MemberType.objects.create(name_pt_br="Equipe Administrativa", name_en="Administrative Staff")
    MemberType.objects.create(name_pt_br="Trainee")
    MemberType.objects.create(name_pt_br="Estagiário", name_en="Intern")


def load_initial_publication_types(apps, schema_editor):
    PublicationType = apps.get_model("portal", "PublicationType")
    PublicationType.objects.create(name_pt_br="Imprensa", name_en="Press")
    PublicationType.objects.create(name_pt_br="Artigo", name_en="Article")


def load_initial_pages(apps, schema_editor):
    Page = apps.get_model("portal", "Page")
    PageParameter = apps.get_model("portal", "PageParameter")

    home = Page.objects.create(title="Home", title_pt_br="Home", slug="home")
    PageParameter.objects.create(
        name="header-blurb-title",
        value_pt_br="Juntos, podemos mais",
        page=home
    )
    PageParameter.objects.create(
        name="header-blurb-text",
        value_pt_br="Trabalhamos para proporcionar segurança jurídica e eficácia às relações empresariais e patrimoniais dos nossos clientes.",
        page=home
    )
    PageParameter.objects.create(
        name="letsgo-blurb-title",
        value_pt_br="Vamos juntos",
        page=home
    )
    PageParameter.objects.create(
        name="letsgo-blurb-text",
        value_pt_br="Aqui devemos reforçar a nossa missão “Juntos, podemos mais”. E por isso temos tantos prêmios que demonstram nosso "
                    "compromisso.",
        page=home
    )
    PageParameter.objects.create(
        name="practice-area-blurb-title",
        value_pt_br="Conheça nossas áreas de atuação",
        page=home
    )
    PageParameter.objects.create(
        name="practice-area-blurb-text",
        value_pt_br="Aqui devemos explicar como atuamos e deixar claro o nosso diferencial ralativo às áreas de atuação. Além disso, "
                    "vou colocar um "
                    "texto a mais",
        page=home
    )
    PageParameter.objects.create(
        name="opportunity-blurb-1-title",
        value_pt_br="Não achou um oportunidade em sua área?",
        page=home
    )
    PageParameter.objects.create(
        name="opportunity-blurb-1-text",
        value_pt_br="Estamos sempre em busca de talentos. Clique no botão abaixo e preencha nosso formulário.",
        page=home
    )
    PageParameter.objects.create(
        name="opportunity-blurb-2-title",
        value_pt_br="Por que trabalhar com a gente?",
        page=home
    )
    PageParameter.objects.create(
        name="opportunity-blurb-2-text",
        value_pt_br="O desenvolvimento de talentos faz parte de nossa cultura organizacional, em busca da alta especialização e qualificação de "
                    "nossa tripulação, para surpreender nossos clientes. Se você se identificou com os nossos valores, acredita que \"juntos, "
                    "podemos mais\"."
                    "\n\n"
                    "Se você se identificou com os nossos valores, acredita que \"juntos, podemos mais\" e pretende fazer parte de um time "
                    "vencedor, candidate-se a uma de nossas oportunidades ou envie-nos seu currículo.",
        page=home
    )

    Page.objects.create(title="Todas as Atuações", title_pt_br="Todas as Atuações", slug="practice-area-list")
    Page.objects.create(title="Atuação", title_pt_br="Atuação", slug="practice-area-detail")
    Page.objects.create(title="Equipe", title_pt_br="Equipe", slug="member-list")
    Page.objects.create(title="Advogado", title_pt_br="Advogado", slug="member-detail")
    Page.objects.create(title="Premiações", title_pt_br="Premiações", slug="award-list")


# Test Data
def load_initial_offices(apps, schema_editor):
    Office = apps.get_model("portal", "Office")
    Office.objects.create(
        country_pt_br="Brasil",
        state_pt_br="PE",
        city_pt_br="Recife",
        neighborhood_pt_br="Pina",
        address_pt_br="Av. Antônio de Góes, 60, JCPM Trade Center, 1º andar",
        postcode="51.010-000",
        gmaps_iframe="<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d37580.30110409138!2d-34.90257723055943!3d-8"
                     ".086940540394998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x7ab1f3733e374f1%3A0x33edd5e97ff13d0a!2sCondom%C3"
                     "%ADnio+do+Edif%C3%ADcio+JCPM+Trade+Center!5e0!3m2!1spt-BR!2sbr!4v1553703438726\" width=\"600\" height=\"450\" frameborder=\"0\" "
                     "style=\"border:0\" allowfullscreen></iframe>",
        phone="+55 (81) 2126.0092",
        email="contatoDFPE@dafonteadv.com.br",
        is_parent=True,
    )
    Office.objects.create(
        country_pt_br="Brasil",
        state_pt_br="SP",
        city_pt_br="São Paulo",
        neighborhood_pt_br="Vila Olímpia",
        address_pt_br="Rua Funchal, 573, conjs 81 e 82, 8º andar, Edifício Aeroporto I",
        gmaps_iframe="<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d58499.39249151906!2d-46.714006300422625!3d-23"
                     ".59672757774452!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ce573804e55a4f%3A0xc9072d90f8966c64!2sR.+Funchal%2C"
                     "+573+-+8%C2%BA+andar+-+Vila+Ol%C3%ADmpia%2C+S%C3%A3o+Paulo+-+SP%2C+04551-060!5e0!3m2!1spt-BR!2sbr!4v1553703876596\" "
                     "width=\"600\" height=\"450\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe>",
        postcode="04.551-910",
        phone="+55 (11) 3814.6930",
        email="contatoDFSP@dafonteadv.com.br",
        is_parent=False,
    )
    Office.objects.create(
        country_pt_br="Brasil",
        state_pt_br="DF",
        city_pt_br="Brasília",
        neighborhood_pt_br="Brazil XXI",
        address_pt_br="Setor Hoteleiro Sul, quadra 06, conjunto A, bloco C, Business",
        postcode="70.316-000",
        gmaps_iframe="<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d61428.63665607575!2d-47.91365896655585!3d-15"
                     ".788674866216367!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x935a3ae8af68f0af%3A0x9cce9f5507df0fa7!2sComplexo"
                     "+Brasil+21!5e0!3m2!1spt-BR!2sbr!4v1553703996325\" width=\"600\" height=\"450\" frameborder=\"0\" style=\"border:0\" "
                     "allowfullscreen></iframe>",
        phone="+55 (61) 3039.8551",
        email="contatoDFDF@dafonteadv.com.br",
        is_parent=False,
    )
    Office.objects.create(
        country_pt_br="Brasil",
        state_pt_br="BA",
        city_pt_br="Salvador",
        neighborhood_pt_br="Parque Bela Vista de Brotas",
        address_pt_br="Av. Antônio Carlos Magalhães, 3247, Edf. Empresarial Delta",
        gmaps_iframe="<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d52308.008919861306!2d-38.49706944383584!3d-12"
                     ".98361606215849!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x7161b47f3bc853b%3A0x13f6dd56be86480d!2sCondom%C3%ADnio"
                     "+do+Edif%C3%ADcio+Empresarial+Delta!5e0!3m2!1spt-BR!2sbr!4v1553704112318\" width=\"600\" height=\"450\" frameborder=\"0\" "
                     "style=\"border:0\" allowfullscreen></iframe>",
        postcode="40.280-000",
        phone="+55 (71) 3351.4373",
        email="contatoDFBA@dafonteadv.com.br",
        is_parent=False,
    )


def load_initial_practice_areas(apps, schema_editor):
    PracticeArea = apps.get_model("portal", "PracticeArea")
    Approach = apps.get_model("portal", "Approach")

    direito_ampresarial = PracticeArea.objects.create(
        name="Direito Empresarial",
        name_pt_br="Direito Empresarial",
        description_pt_br="Na consultoria e assessoria em Direito Societário e Contratual, atendemos empresas de diversos setores e portes, "
                          "auxiliando na estruturação societária e contratual de investimentos, em operações de fusão e aquisição de empresas, "
                          "na construção de parcerias comerciais, na negociação de contratos e disputas societárias."
    )
    Approach.objects.create(text="Compra, venda, fusão, cisão e incorporação de empresas (M&A)", practice_area=direito_ampresarial)
    Approach.objects.create(text="Estruturação societária e contratual de investimentos", practice_area=direito_ampresarial)
    Approach.objects.create(text="Auditoria para venture capital e private equity", practice_area=direito_ampresarial)
    Approach.objects.create(text="Reorganização societária e governança corporativa", practice_area=direito_ampresarial)
    Approach.objects.create(text="Alianças, joint ventures e operações internacionais", practice_area=direito_ampresarial)
    Approach.objects.create(text="Elaboração, análise e negociação de contratos empresariais em geral", practice_area=direito_ampresarial)

    PracticeArea.objects.create(
        name="Direito Tributário",
        name_pt_br="Direito Tributário",
        description_pt_br="Com advogados especializados em Direito Tributário, que têm formação jurídica e contábil e expertise na elaboração "
                          "de planejamento e consultoria tributária, trabalhamos em auditorias para operações societárias e atuamos em âmbito "
                          "administrativo e judicial. Alguns de nossos sócios têm experiência como julgadores de Tribunais Administrativos."
                          "\n\n"
                          "A assessoria tributária é desenvolvida com o objetivo de evitar demandas entre os seus clientes "
                          "e o fisco. Para isso, a da Fonte Advogados desempenha as suas atividades em conjunto com os setores fiscal e "
                          "contábil de seus clientes, a fim de que as decisões empresariais sejam sempre influenciadas pelo binômio segurança "
                          "jurídica e economia fiscal. Essa assessoria é desenvolvida igualmente para empresas brasileiras com negócios no "
                          "exterior, como também para empresas estrangeiras com atividades no Brasil, nos mais diversos setores da economia."
    )
    PracticeArea.objects.create(
        name="Direito Trabalhista e Relações Sindicais",
        name_pt_br="Direito Trabalhista e Relações Sindicais",
        description_pt_br="Nossas atividades em Direito do Trabalho são realizadas de forma integrada a diversas outras áreas de atuação do "
                          "escritório, em especial a previdenciária, societária e a contratual, o que permite o desenvolvimento da assessoria "
                          "jurídica completa em assuntos trabalhistas empresariais, tanto no âmbito do direito individual quanto no coletivo, "
                          "envolvendo a assessoria consultiva e contenciosa, administrativa e judicial."
                          "\n\n"
                          "No âmbito do direito individual, atuamos com o máximo de segurança na prevenção de passivos judiciais trabalhistas, "
                          "incluindo o patrocínio dos interesses dos nossos clientes em processos judiciais em trâmite perante Tribunais "
                          "Regionais e Superior do Trabalho."
                          "\n\n"
                          "No direito coletivo do trabalho, também participamos ativamente de negociações coletivas de trabalho, na elaboração "
                          "de convenções e acordos coletivos de trabalho, bem como nas audiências junto ao Ministério do Trabalho e Emprego e "
                          "no Ministério Público do Trabalho."
                          "\n\n"
                          "No âmbito administrativo do trabalho, temos expertise em apresentação de defesas e recursos administrativos "
                          "provenientes de autuações do Ministério do Trabalho e Emprego. Temos presença efetiva na consultoria preventiva, "
                          "com a elaboração de orientações e pareceres visando mitigar as contendas e os passivos ocultos."
    )
    PracticeArea.objects.create(
        name="Direito Civil",
        name_pt_br="Direito Civil",
        description_pt_br="-"
    )
    PracticeArea.objects.create(
        name="Direito Administrativo",
        name_pt_br="Direito Administrativo",
        description_pt_br="-"
    )
    PracticeArea.objects.create(
        name="Arbitragem",
        name_pt_br="Arbitragem",
        description_pt_br="-"
    )
    PracticeArea.objects.create(
        name="Direito Ambiental",
        name_pt_br="Direito Ambiental",
        description_pt_br="-"
    )
    PracticeArea.objects.create(
        name="Contencioso e Consultoria Processual",
        name_pt_br="Contencioso e Consultoria Processual",
        description_pt_br="-"
    )
    PracticeArea.objects.create(
        name="Direito de Família e Sucessões",
        name_pt_br="Direito de Família e Sucessões",
        description_pt_br="-"
    )
    PracticeArea.objects.create(
        name="Direito Imobiliário",
        name_pt_br="Direito Imobiliário",
        description_pt_br="-"
    )
    PracticeArea.objects.create(
        name="Direito Penal Empresarial",
        name_pt_br="Direito Penal Empresarial",
        description_pt_br="-"
    )
    PracticeArea.objects.create(
        name="Direito Internacional",
        name_pt_br="Direito Internacional",
        description_pt_br="-"
    )
    PracticeArea.objects.create(
        name="Propriedade Intelectual e Novas Tecnologias",
        name_pt_br="Propriedade Intelectual e Novas Tecnologias",
        description_pt_br="-"
    )
    PracticeArea.objects.create(
        name="Recuperação Judicial e Falência",
        name_pt_br="Recuperação Judicial e Falência",
        description_pt_br="-"
    )
    PracticeArea.objects.create(
        name="Direito de Energia",
        name_pt_br="Direito de Energia",
        description_pt_br="-"
    )
    PracticeArea.objects.create(
        name="Infraestrutura",
        name_pt_br="Infraestrutura",
        description_pt_br="-"
    )
    PracticeArea.objects.create(
        name="Franquias",
        name_pt_br="Franquias",
        description_pt_br="-"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_initial_user),
        migrations.RunPython(load_initial_members_types),
        migrations.RunPython(load_initial_publication_types),
        migrations.RunPython(load_initial_pages),
        migrations.RunPython(load_initial_offices),
        migrations.RunPython(load_initial_practice_areas),
    ]
