# Generated by Django 2.1.7 on 2019-04-24 21:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_load_intial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='award',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=100, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='award',
            name='description_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=100, null=True, verbose_name='Descrição'),
        ),
    ]
