# Generated by Django 2.1.7 on 2019-04-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190424_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageparameter',
            name='value',
            field=models.TextField(blank=True, default='', verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='pageparameter',
            name='value_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='pageparameter',
            name='value_pt_br',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Valor'),
        ),
    ]
