# Generated by Django 2.1.7 on 2019-04-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190426_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlawyer',
            name='phone',
            field=models.CharField(default='', max_length=19, verbose_name='Telefone'),
        ),
    ]
