# Generated by Django 2.1.7 on 2019-04-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20190429_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlawyer',
            name='other_activities',
            field=models.CharField(default='', max_length=250, verbose_name='Outras Atividades'),
        ),
    ]
