# Generated by Django 2.1.7 on 2019-04-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20190429_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='related_members',
            field=models.ManyToManyField(blank=True, related_name='related_events', to='portal.Member', verbose_name='Membros Relacionados'),
        ),
    ]
