# Generated by Django 2.1.7 on 2019-04-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_event_related_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='related_members',
        ),
        migrations.AddField(
            model_name='event',
            name='related_lawyers',
            field=models.ManyToManyField(blank=True, related_name='related_lawyers', to='portal.MemberLawyer', verbose_name='Advogados Relacionados'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_trainees',
            field=models.ManyToManyField(blank=True, related_name='related_trainees', to='portal.MemberTrainee', verbose_name='Trainees Relacionados'),
        ),
    ]
