# Generated by Django 2.1.7 on 2019-04-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20190429_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='related_lawyers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='related_trainees',
        ),
        migrations.AddField(
            model_name='event',
            name='related_events_lawyers',
            field=models.ManyToManyField(blank=True, related_name='related_events_lawyers', to='portal.MemberLawyer', verbose_name='Advogados Relacionados'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_events_trainees',
            field=models.ManyToManyField(blank=True, related_name='related_events_trainees', to='portal.MemberTrainee', verbose_name='Trainees Relacionados'),
        ),
    ]
