# Generated by Django 2.1.7 on 2019-04-30 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_publication_content'),
        ('portal', '0011_auto_20190429_1852'),
    ]

    operations = [
    ]
