# Generated by Django 2.1.7 on 2019-05-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_merge_20190430_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='award',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='awardmembers',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='language',
            name='flag',
            field=models.ImageField(upload_to='', verbose_name='Bandeira'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='page',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem de Fundo'),
        ),
        migrations.AlterField(
            model_name='pageparameter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='pageparameter',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='pageparameter',
            name='file_pt_br',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='file_pt_br',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='siteparameter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='siteparameter',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='siteparameter',
            name='file_pt_br',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='socialentity',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='specializationsector',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='specializationsector',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='specializationsector',
            name='file_pt_br',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='specializationsector',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
    ]
