# Generated by Django 2.1.7 on 2019-05-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_remove_language_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicearea',
            name='file',
        ),
        migrations.RemoveField(
            model_name='practicearea',
            name='file_en',
        ),
        migrations.RemoveField(
            model_name='practicearea',
            name='file_pt_br',
        ),
        migrations.RemoveField(
            model_name='specializationsector',
            name='file',
        ),
        migrations.RemoveField(
            model_name='specializationsector',
            name='file_en',
        ),
        migrations.RemoveField(
            model_name='specializationsector',
            name='file_pt_br',
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Capa do evento'),
        ),
        migrations.AlterField(
            model_name='page',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Capa da página'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Capa da página'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, default='', max_length=50, null=True, upload_to='', verbose_name='Anexo PDF'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='file_en',
            field=models.FileField(blank=True, default='', max_length=50, null=True, upload_to='', verbose_name='Anexo PDF'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='file_pt_br',
            field=models.FileField(blank=True, default='', max_length=50, null=True, upload_to='', verbose_name='Anexo PDF'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Capa da publicação'),
        ),
        migrations.AlterField(
            model_name='socialentity',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo da entidade social'),
        ),
        migrations.AlterField(
            model_name='specializationsector',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Capa da página'),
        ),
    ]
