# Generated by Django 2.1.7 on 2019-05-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20190502_1659'),
    ]

    database_operations = [
        migrations.AlterModelTable('membertype', 'members_membertype'),
        migrations.AlterModelTable('jobtitle', 'members_jobtitle'),
        migrations.AlterModelTable('member', 'members_member'),
        migrations.AlterModelTable('memberlawyer', 'members_memberlawyer'),
        migrations.AlterModelTable('memberadministrativestaff', 'members_memberadministrativestaff'),
        migrations.AlterModelTable('membertrainee', 'members_membertrainee'),
        migrations.AlterModelTable('memberintern', 'members_memberintern'),
    ]

    state_operations = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
