# Generated by Django 2.1.7 on 2019-05-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20190502_1908'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='member',
            name='type',
        ),
        migrations.RemoveField(
            model_name='memberadministrativestaff',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='memberadministrativestaff',
            name='member',
        ),
        migrations.RemoveField(
            model_name='memberintern',
            name='member',
        ),
        migrations.RemoveField(
            model_name='memberintern',
            name='practice_areas',
        ),
        migrations.RemoveField(
            model_name='memberlawyer',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='memberlawyer',
            name='member',
        ),
        migrations.RemoveField(
            model_name='memberlawyer',
            name='practice_areas',
        ),
        migrations.RemoveField(
            model_name='membertrainee',
            name='member',
        ),
        migrations.RemoveField(
            model_name='membertrainee',
            name='practice_areas',
        ),
        migrations.DeleteModel(
            name='JobTitle',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='MemberAdministrativeStaff',
        ),
        migrations.DeleteModel(
            name='MemberIntern',
        ),
        migrations.DeleteModel(
            name='MemberLawyer',
        ),
        migrations.DeleteModel(
            name='MemberTrainee',
        ),
        migrations.DeleteModel(
            name='MemberType',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
