# Generated by Django 2.1.7 on 2019-05-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_state_delete_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nome')),
                ('email', models.CharField(default='', max_length=70, verbose_name='E-mail')),
                ('telefone', models.CharField(default='', max_length=20, verbose_name='Telefone')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
