# Generated by Django 2.1.7 on 2019-05-02 23:01

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='requirements',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=1500, verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=1000, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=1000, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=1000, null=True, verbose_name='Descrição'),
        ),
    ]
