# Generated by Django 2.1.7 on 2019-05-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_auto_20190502_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='Titulo')),
                ('description', models.TextField(default='', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'valor',
                'verbose_name_plural': 'valores',
            },
        ),
    ]
