# Generated by Django 2.1.7 on 2019-05-06 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproachSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto')),
                ('text_pt_br', models.TextField(null=True, verbose_name='Texto')),
                ('text_en', models.TextField(null=True, verbose_name='Texto')),
                ('specialization_sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approaches', to='portal.SpecializationSector', verbose_name='Setor de Especialização')),
            ],
            options={
                'verbose_name': 'solução',
                'verbose_name_plural': 'soluções',
            },
        ),
        migrations.AlterUniqueTogether(
            name='approachsector',
            unique_together={('specialization_sector', 'text')},
        ),
    ]
