# Generated by Django 2.1.7 on 2019-05-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_auto_20190506_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='related_practice_areas',
            field=models.ManyToManyField(blank=True, related_name='related_areas', to='portal.PracticeArea', verbose_name='Áreas de Atuação Relacionadas'),
        ),
        migrations.AddField(
            model_name='publication',
            name='relates_specialization_sector',
            field=models.ManyToManyField(blank=True, related_name='related_sectors', to='portal.SpecializationSector', verbose_name='Setores de Especialização Relacionados'),
        ),
    ]