# Generated by Django 2.1.7 on 2019-05-07 17:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_auto_20190506_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='relates_specialization_sector',
        ),
        migrations.AddField(
            model_name='event',
            name='related_practice_areas',
            field=models.ManyToManyField(blank=True, related_name='related_event_areas', to='portal.PracticeArea', verbose_name='Áreas de Atuação Relacionadas'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_specialization_sector',
            field=models.ManyToManyField(blank=True, related_name='related_event_sectors', to='portal.SpecializationSector', verbose_name='Setores de Especialização Relacionados'),
        ),
        migrations.AddField(
            model_name='publication',
            name='related_specialization_sector',
            field=models.ManyToManyField(blank=True, related_name='related_publication_sectors', to='portal.SpecializationSector', verbose_name='Setores de Especialização Relacionados'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='related_practice_areas',
            field=models.ManyToManyField(blank=True, related_name='related_publication_areas', to='portal.PracticeArea', verbose_name='Áreas de Atuação Relacionadas'),
        ),
    ]
