# Generated by Django 2.1.7 on 2019-05-07 20:50

import ckeditor_uploader.fields
import dafonte_portal.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_auto_20190506_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliate',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='logo',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='logo_footer',
            field=models.ImageField(blank=True, null=True, upload_to=dafonte_portal.utils.upload_to, verbose_name='Logo para footer'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='logo_normal',
            field=models.ImageField(blank=True, null=True, upload_to=dafonte_portal.utils.upload_to, verbose_name='Logo para página de quem somos'),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo_footer',
            field=models.ImageField(blank=True, null=True, upload_to=dafonte_portal.utils.upload_to, verbose_name='Logo para footer'),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo_normal',
            field=models.ImageField(blank=True, null=True, upload_to=dafonte_portal.utils.upload_to, verbose_name='Logo para página de quem somos'),
        ),
        migrations.AlterField(
            model_name='award',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='award',
            name='title_en',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='award',
            name='title_pt_br',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='awardmembers',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=3000, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=3000, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=3000, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='requirements',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=3000, verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='title_en',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='title_pt_br',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_pt_br',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_en',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_pt_br',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='values',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Titulo'),
        ),
    ]
