# Generated by Django 2.1.7 on 2019-05-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_auto_20190507_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardmembers',
            name='member',
        ),
        migrations.DeleteModel(
            name='AwardMembers',
        ),
    ]
