# Generated by Django 2.1.7 on 2019-05-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_auto_20190507_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description_pt_br',
        ),
    ]
