# Generated by Django 2.1.7 on 2019-05-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_auto_20190508_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
    ]
