# Generated by Django 2.1.7 on 2019-07-30 21:41

from django.db import migrations, models

def migrate_oportunity_local_data(apps, schema_editor):
    # MIGRATE LOCAL PATTER ( Recife/PE | Brasília/DF ) to ( RC | BS )
    OpportunityModel = apps.get_model('portal', 'Opportunity')
    for opportunity in OpportunityModel.objects.all():
        if (opportunity.city == 'Recife/PE'):
            opportunity.city = 'RC'
            opportunity.city_en = 'RC'
            opportunity.city_pt_br = 'RC'
            opportunity.save()
        elif (opportunity.city == 'Brasília/DF'):
            opportunity.city = 'BS'
            opportunity.city_en = 'BS'
            opportunity.city_pt_br = 'BS'
            opportunity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_opportunity_active'),
    ]

    operations = [
        migrations.RunPython(migrate_oportunity_local_data),
        migrations.AddField(
            model_name='opportunity',
            name='role',
            field=models.CharField(blank=True, choices=[('LAWYER', 'Advogado'), ('INTERN', 'Estagiário'), ('TRAINEE', 'Trainee')], max_length=20, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='city',
            field=models.CharField(blank=True, choices=[('RC', 'Recife-PE'), ('SL', 'Salvador-BA'), ('BS', 'Brasília-DF'), ('SP', 'São Paulo-SP')], max_length=20, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='city_en',
            field=models.CharField(blank=True, choices=[('RC', 'Recife-PE'), ('SL', 'Salvador-BA'), ('BS', 'Brasília-DF'), ('SP', 'São Paulo-SP')], max_length=20, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='city_pt_br',
            field=models.CharField(blank=True, choices=[('RC', 'Recife-PE'), ('SL', 'Salvador-BA'), ('BS', 'Brasília-DF'), ('SP', 'São Paulo-SP')], max_length=20, null=True, verbose_name='Cidade'),
        ),
    ]
