# Generated by Django 2.1.7 on 2020-07-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_auto_20200619_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['-is_parent', 'office_order'], 'verbose_name': 'escritório'},
        ),
        migrations.AddField(
            model_name='affiliate',
            name='site',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='event',
            name='sympla_button',
            field=models.TextField(blank=True, null=True, verbose_name='Sympla - Botão de ingressos'),
        ),
        migrations.AddField(
            model_name='event',
            name='sympla_grid',
            field=models.TextField(blank=True, null=True, verbose_name='Sympla - Grid de ingressos'),
        ),
        migrations.AddField(
            model_name='office',
            name='office_order',
            field=models.PositiveSmallIntegerField(default=99, verbose_name='Ordem de exibição'),
        ),
        migrations.AddField(
            model_name='partner',
            name='site',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Site'),
        ),
    ]
