# Generated by Django 2.1.7 on 2021-01-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_auto_20210125_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='role',
        ),
    ]
