# Generated by Django 2.1.7 on 2021-01-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_auto_20210126_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunityrole',
            options={'verbose_name': 'cargo', 'verbose_name_plural': 'cargos'},
        ),
        migrations.AlterField(
            model_name='opportunityrole',
            name='role_type',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Tipo'),
        ),
    ]
