# Generated by Django 2.2 on 2023-04-02 18:04

import ckeditor.fields
from django.db import migrations


def load_initial_publication_types(apps, schema_editor):
    PublicationType = apps.get_model("portal", "PublicationType")
    PublicationType.objects.create(name_pt_br="Informativo", name_en="Informative")

class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_auto_20210126_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approach',
            options={'ordering': ('pk',), 'verbose_name': 'solução', 'verbose_name_plural': 'soluções'},
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='description_pt_br',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='specializationsector',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='specializationsector',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='specializationsector',
            name='description_pt_br',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.RunPython(load_initial_publication_types),
    ]
