# Generated by Django 2.1.7 on 2019-04-30 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0002_auto_20190430_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_applications', to='portal.Opportunity'),
        ),
    ]
