# Generated by Django 2.1.7 on 2019-05-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0003_auto_20190430_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalexperience',
            name='periodo',
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='date_begin',
            field=models.DateField(blank=True, default=None, verbose_name='Data de Inicio'),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='date_finish',
            field=models.DateField(blank=True, default=None, verbose_name='Data de término'),
        ),
    ]
