# Generated by Django 2.1.7 on 2019-05-09 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0005_auto_20190508_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_applications', to='portal.Opportunity'),
        ),
    ]
