# Generated by Django 2.1.7 on 2019-07-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0006_auto_20190509_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='local',
            field=models.CharField(choices=[('RC', 'Recife'), ('SL', 'Salvador'), ('BS', 'Brasília'), ('SP', 'São Paulo')], default='', max_length=1, verbose_name='Localidade'),
        ),
        migrations.AddField(
            model_name='application',
            name='role',
            field=models.CharField(choices=[('LAWYER', 'Advogado'), ('INTERN', 'Estagiário'), ('TRAINEE', 'Trainee')], default='', max_length=1, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=19, verbose_name='Telefone'),
        ),
    ]
