# Generated by Django 2.1.7 on 2019-07-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0009_auto_20190730_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='local',
            field=models.CharField(blank=True, choices=[('RC', 'Recife'), ('SL', 'Salvador'), ('BS', 'Brasília'), ('SP', 'São Paulo')], max_length=20, verbose_name='Localidade'),
        ),
        migrations.AlterField(
            model_name='application',
            name='role',
            field=models.CharField(blank=True, choices=[('LAWYER', 'Advogado'), ('INTERN', 'Estagiário'), ('TRAINEE', 'Trainee')], max_length=20, verbose_name='Cargo'),
        ),
    ]
