# Generated by Django 2.1.7 on 2019-07-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0010_auto_20190730_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='period',
            field=models.CharField(blank=True, choices=[('1', '1º Período'), ('2', '2º Período'), ('3', '3º Período'), ('4', '4º Período'), ('5', '5º Período'), ('6', '6º Período'), ('7', '7º Período'), ('8', '8º Período'), ('9', '9º Período'), ('10', '10º Período'), ('12', '12º Período')], max_length=20, verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='academic',
            name='shift',
            field=models.CharField(blank=True, choices=[('M', 'Manhã'), ('T', 'Trade'), ('N', 'Noite')], max_length=20, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(default='', max_length=19, verbose_name='Telefone'),
        ),
    ]
