# Generated by Django 2.1.7 on 2019-07-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0011_auto_20190730_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='in_progress',
            field=models.BooleanField(blank='True', default=False, verbose_name='Em progresso'),
        ),
        migrations.AlterField(
            model_name='academic',
            name='period',
            field=models.CharField(blank=True, choices=[('X', 'Concluido'), ('1', '1º Período'), ('2', '2º Período'), ('3', '3º Período'), ('4', '4º Período'), ('5', '5º Período'), ('6', '6º Período'), ('7', '7º Período'), ('8', '8º Período'), ('9', '9º Período'), ('10', '10º Período'), ('12', '12º Período')], max_length=20, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='academic',
            name='shift',
            field=models.CharField(blank=True, choices=[('X', 'Concluido'), ('M', 'Manhã'), ('T', 'Trade'), ('N', 'Noite')], max_length=20, verbose_name='Turno'),
        ),
    ]
