# Generated by Django 2.1.7 on 2019-08-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0012_auto_20190731_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Oportunidade Ativa'),
        ),
    ]
