# Generated by Django 2.1.7 on 2019-08-09 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0014_application_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Enviado em'),
        ),
    ]
