# Generated by Django 2.1.7 on 2019-08-09 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_auto_20190730_1848'),
        ('applying', '0016_auto_20190809_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='practice_areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_applications', to='portal.PracticeArea'),
        ),
        migrations.AddField(
            model_name='application',
            name='specialization_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_applications', to='portal.SpecializationSector'),
        ),
    ]
