# Generated by Django 2.1.7 on 2019-08-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0017_auto_20190809_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='specialization_sector',
            new_name='specialization_sectors',
        ),
    ]
