# Generated by Django 2.1.7 on 2019-08-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0018_auto_20190809_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='active',
        ),
        migrations.AlterField(
            model_name='academic',
            name='shift',
            field=models.CharField(blank=True, choices=[('X', 'Concluido'), ('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=20, verbose_name='Turno'),
        ),
    ]
