# Generated by Django 2.1.7 on 2019-09-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0019_auto_20190813_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='intend_area',
            field=models.TextField(blank=True, verbose_name='Área Pretendida'),
        ),
    ]
