# Generated by Django 2.1.7 on 2019-09-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0021_auto_20190910_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='intend_area',
            field=models.CharField(blank=True, max_length=150, verbose_name='Área Pretendida'),
        ),
    ]
