# Generated by Django 2.1.7 on 2020-07-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0023_auto_20200619_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='incomplete_course',
            field=models.BooleanField(blank=True, default=False, verbose_name='Curso incompleto'),
        ),
    ]
