# Generated by Django 2.1.7 on 2020-09-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0024_academic_incomplete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='actual_function',
            field=models.BooleanField(blank=True, default=False, verbose_name='Cargo Atual'),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='date_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Data de término'),
        ),
    ]
