# Generated by Django 2.1.7 on 2020-09-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0025_auto_20200901_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationlanguage',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Básico'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], max_length=30, null=True, verbose_name='Nível'),
        ),
    ]
