# Generated by Django 2.1.7 on 2021-01-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applying', '0027_auto_20210125_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_downloaded',
            field=models.BooleanField(default=False, verbose_name='Visualizado'),
        ),
    ]
