# Generated by Django 2.1.7 on 2019-05-02 19:56

import dafonte_portal.utils
from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0020_alter_members_tables'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('name_pt_br', models.CharField(max_length=50, null=True, verbose_name='Nome')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'título da função',
                'verbose_name_plural': 'titulos das funções',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='Sobrenome')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=dafonte_portal.utils.upload_to, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'membro',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='MemberAdministrativeStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.JobTitle', verbose_name='Nome da Função')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_staff', to='members.Member')),
            ],
            options={
                'verbose_name': 'membro da equipe administrativa',
                'verbose_name_plural': 'membros da equipe administrativa',
                'ordering': ['member__first_name'],
            },
            bases=(models.Model, members.models.MemberChild),
        ),
        migrations.CreateModel(
            name='MemberIntern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intern', to='members.Member')),
                ('practice_areas', models.ManyToManyField(related_name='interns', to='portal.PracticeArea')),
            ],
            options={
                'verbose_name': 'estagiário',
                'ordering': ['member__first_name'],
            },
            bases=(models.Model, members.models.MemberChild),
        ),
        migrations.CreateModel(
            name='MemberLawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('phone', models.CharField(default='', max_length=19, verbose_name='Telefone')),
                ('profile', models.TextField(verbose_name='Perfil')),
                ('profile_pt_br', models.TextField(null=True, verbose_name='Perfil')),
                ('profile_en', models.TextField(null=True, verbose_name='Perfil')),
                ('academic_formation', models.TextField(verbose_name='Formação Acadêmica')),
                ('academic_formation_pt_br', models.TextField(null=True, verbose_name='Formação Acadêmica')),
                ('academic_formation_en', models.TextField(null=True, verbose_name='Formação Acadêmica')),
                ('professional_experience', models.TextField(verbose_name='Experiência Profisisonal')),
                ('professional_experience_pt_br', models.TextField(null=True, verbose_name='Experiência Profisisonal')),
                ('professional_experience_en', models.TextField(null=True, verbose_name='Experiência Profisisonal')),
                ('awards_and_publications', models.TextField(verbose_name='Prêmios e Publicações')),
                ('awards_and_publications_pt_br', models.TextField(null=True, verbose_name='Prêmios e Publicações')),
                ('awards_and_publications_en', models.TextField(null=True, verbose_name='Prêmios e Publicações')),
                ('other_activities', models.TextField(default='', verbose_name='Outras Atividades')),
                ('languages', models.ManyToManyField(related_name='lawyers', to='portal.Language', verbose_name='Idiomas')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer', to='members.Member')),
                ('practice_areas', models.ManyToManyField(related_name='lawyers', to='portal.PracticeArea', verbose_name='Áreas de Atuação')),
            ],
            options={
                'verbose_name': 'advogado',
                'ordering': ['member__first_name'],
            },
            bases=(models.Model, members.models.MemberChild),
        ),
        migrations.CreateModel(
            name='MemberTrainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainee', to='members.Member')),
                ('practice_areas', models.ManyToManyField(related_name='trainees', to='portal.PracticeArea', verbose_name='Áreas de Atuação')),
            ],
            options={
                'verbose_name': 'trainee',
                'ordering': ['member__first_name'],
            },
            bases=(models.Model, members.models.MemberChild),
        ),
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('name_pt_br', models.CharField(max_length=50, null=True, verbose_name='Nome')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'tipo de membro',
                'verbose_name_plural': 'tipos de membro',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.MemberType', verbose_name='Tipo de Membro'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
