# Generated by Django 2.1.7 on 2019-05-03 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyAdministrativeStaff',
            fields=[
            ],
            options={
                'verbose_name': 'membro da equipe administrativa',
                'verbose_name_plural': 'membros da equipe administrativa',
                'proxy': True,
                'indexes': [],
            },
            bases=('members.member',),
        ),
        migrations.CreateModel(
            name='ProxyIntern',
            fields=[
            ],
            options={
                'verbose_name': 'estagiário',
                'verbose_name_plural': 'estagiários',
                'proxy': True,
                'indexes': [],
            },
            bases=('members.member',),
        ),
        migrations.CreateModel(
            name='ProxyLawyer',
            fields=[
            ],
            options={
                'verbose_name': 'advogado',
                'verbose_name_plural': 'advogados',
                'proxy': True,
                'indexes': [],
            },
            bases=('members.member',),
        ),
        migrations.CreateModel(
            name='ProxyTrainee',
            fields=[
            ],
            options={
                'verbose_name': 'trainee',
                'verbose_name_plural': 'trainees',
                'proxy': True,
                'indexes': [],
            },
            bases=('members.member',),
        ),
    ]
