# Generated by Django 2.1.7 on 2019-05-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_auto_20190506_1535'),
        ('members', '0003_memberlawyer_vcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlawyer',
            name='specialization_sector',
            field=models.ManyToManyField(related_name='lawyers', to='portal.SpecializationSector', verbose_name='Setor de Especialização'),
        ),
    ]
