# Generated by Django 2.1.7 on 2019-05-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_memberlawyer_specialization_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberlawyer',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='memberlawyer',
            name='profile_en',
        ),
        migrations.RemoveField(
            model_name='memberlawyer',
            name='profile_pt_br',
        ),
    ]
