# Generated by Django 2.1.7 on 2019-05-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20190507_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlawyer',
            name='other_activities_en',
            field=models.TextField(default='', null=True, verbose_name='Outras Atividades'),
        ),
        migrations.AddField(
            model_name='memberlawyer',
            name='other_activities_pt_br',
            field=models.TextField(default='', null=True, verbose_name='Outras Atividades'),
        ),
    ]
