# Generated by Django 2.1.7 on 2019-05-07 21:57

import ckeditor_uploader.fields
import dafonte_portal.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20190507_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=dafonte_portal.utils.upload_to, verbose_name='Imagem')),
                ('publication_date', models.DateField(default=datetime.datetime.now, verbose_name='Data de Publicação')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Título')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'prêmio de advogados',
            },
        ),
        migrations.AddField(
            model_name='memberlawyer',
            name='awards',
            field=models.ManyToManyField(related_name='lawyers', to='members.AwardMembers', verbose_name='Prêmios'),
        ),
    ]
