# Generated by Django 2.1.7 on 2019-05-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20190507_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardmembers',
            options={'verbose_name': 'prêmios de advogado'},
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='awards',
            field=models.ManyToManyField(null=True, related_name='lawyers', to='members.AwardMembers', verbose_name='Prêmios'),
        ),
    ]
