# Generated by Django 2.1.7 on 2019-05-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20190507_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlawyer',
            name='awards_and_publications',
            field=models.TextField(blank=True, verbose_name='Prêmios e Publicações'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='awards_and_publications_en',
            field=models.TextField(blank=True, null=True, verbose_name='Prêmios e Publicações'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='awards_and_publications_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Prêmios e Publicações'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='other_activities',
            field=models.TextField(blank=True, default='', verbose_name='Outras Atividades'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='other_activities_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Outras Atividades'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='other_activities_pt_br',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Outras Atividades'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='specialization_sector',
            field=models.ManyToManyField(blank=True, related_name='lawyers', to='portal.SpecializationSector', verbose_name='Setor de Especialização'),
        ),
    ]
