# Generated by Django 2.1.7 on 2019-09-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20190910_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberintern',
            name='practice_areas',
            field=models.ManyToManyField(blank=True, related_name='interns', to='portal.PracticeArea'),
        ),
        migrations.AlterField(
            model_name='memberintern',
            name='specialization_sectors',
            field=models.ManyToManyField(blank=True, related_name='interns', to='portal.SpecializationSector'),
        ),
        migrations.AlterField(
            model_name='membertrainee',
            name='practice_areas',
            field=models.ManyToManyField(blank=True, related_name='trainees', to='portal.PracticeArea', verbose_name='Áreas de Atuação'),
        ),
        migrations.AlterField(
            model_name='membertrainee',
            name='specialization_sectors',
            field=models.ManyToManyField(blank=True, related_name='trainees', to='portal.SpecializationSector'),
        ),
    ]
