# Generated by Django 2.1.7 on 2020-10-23 12:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20190910_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlawyer',
            name='academic_formation',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Formação Acadêmica'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='academic_formation_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Formação Acadêmica'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='academic_formation_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Formação Acadêmica'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='awards_and_publications',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Prêmios e Publicações'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='awards_and_publications_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Prêmios e Publicações'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='awards_and_publications_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Prêmios e Publicações'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='other_activities',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Outras Atividades'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='other_activities_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Outras Atividades'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='other_activities_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Outras Atividades'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='professional_experience',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Experiência Profisisonal'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='professional_experience_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Experiência Profisisonal'),
        ),
        migrations.AlterField(
            model_name='memberlawyer',
            name='professional_experience_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Experiência Profisisonal'),
        ),
    ]
